import type { Question } from '@/types/survey';

export const QUESTIONS: Question[] = [
  {
    id: 'institution',
    type: 'single-choice',
    category: 'About You',
    question: 'Which institution do you currently attend?',
    subtitle: 'We want to understand which campuses face the biggest challenges.',
    options: [
      'University of Nigeria, Enugu Campus (UNEC)',
      'Enugu State University (ESUT)',
      'Institute of Management & Technology (IMT)',
      'Godfrey Okoye University',
      'Caritas University',
      'Other institution',
    ],
  },
  {
    id: 'living_situation',
    type: 'single-choice',
    category: 'About You',
    question: 'Where do you currently live?',
    subtitle: 'Your living situation shapes how and where you find items.',
    options: [
      'School hostel',
      'Off-campus with roommates',
      'Off-campus alone',
      'With family',
    ],
  },
  {
    id: 'hardest_item',
    type: 'single-choice',
    category: 'Your Experience',
    question: 'Which household item has been the hardest to find recently?',
    subtitle: 'Think about the last time you needed something for your room or kitchen.',
    options: [
      'Bed',
      'Mattress',
      'Chair',
      'Reading table',
      'Wardrobe',
      'Fan',
      'Kitchen items',
      'Electronics',
      'Laptops',
      'Gadgets',
      'Phones',
      'Other',
    ],
  },
  {
    id: 'first_search',
    type: 'single-choice',
    category: 'Your Experience',
    question: 'Where did you first search for it?',
    subtitle: 'Your first instinct tells us where students naturally go.',
    options: [
      'WhatsApp groups',
      'Friends & word of mouth',
      'Jiji',
      'Facebook Marketplace',
      'Physical market',
      'Other',
    ],
  },
  {
    id: 'found_item',
    type: 'yes-no-followup',
    category: 'Your Experience',
    question: 'Did you eventually find the item you were looking for?',
    subtitle: 'Be honest — your experience, good or bad, helps us build better.',
    options: ['Yes, I found it', 'No, I gave up'],
    followUp: {
      trigger: 'no',
      label: 'What stopped you from finding it?',
      placeholder: "e.g. Prices were too high, couldn't find a trusted seller, delivery was a problem...",
    },
  },
  {
    id: 'biggest_challenge',
    type: 'single-choice',
    category: 'The Challenges',
    question: 'What was the biggest challenge in that experience?',
    subtitle: 'Pick the single biggest frustration you faced.',
    options: [
      "Trust — I wasn't sure if the seller was genuine",
      'Price — the cost was unreasonable',
      'Availability — nobody had what I needed',
      'Quality — items were damaged or misrepresented',
      'Delivery — no one could bring it to me',
      'Slow response — sellers took too long to reply',
      'Something else',
    ],
  },
  {
    id: 'trust_vs_price',
    type: 'single-choice',
    category: 'What Matters Most',
    question: "When buying from someone you don't know, what matters most?",
    subtitle: 'Rank your top priority — only one answer.',
    options: [
      "Trust — I need to know they're genuine",
      'Price — I need it to be affordable',
      'Quality — I need it to be exactly as described',
      'Fast response — I need quick answers',
      'Delivery — I need it brought to me',
      'Convenience — I need the whole process to be easy',
    ],
  },
  {
    id: 'cancelled_purchase',
    type: 'yes-no-followup',
    category: 'Trust & Safety',
    question: "Have you ever cancelled a purchase because you didn't trust the seller?",
    subtitle: 'This is more common than people admit. Your honesty shapes what we build.',
    options: ['Yes, I cancelled', "No, I've always gone through"],
    followUp: {
      trigger: 'yes',
      label: 'Tell us briefly what happened.',
      placeholder: 'e.g. The seller stopped responding, the photos looked fake, I couldn\'t verify their identity...',
    },
  },
  {
    id: 'paid_for_delivery',
    type: 'yes-no-followup',
    category: 'Cost of Buying',
    question: 'Have you ever paid extra for transportation or delivery?',
    subtitle: 'Hidden delivery costs are a real barrier we want to solve.',
    options: ["Yes, I've paid extra", "No, I've always collected myself"],
    followUp: {
      trigger: 'yes',
      label: 'How much extra did you pay? (approximate is fine)',
      placeholder: 'e.g. ₦500, ₦2,000, ₦5,000...',
    },
  },
  {
    id: 'platform_preference',
    type: 'single-choice',
    category: 'Platform Preference',
    question: 'How would you prefer to access a student marketplace in Enugu?',
    subtitle: 'Be honest — we are building this around how you actually live and use your phone.',
    options: [
      'A WhatsApp group or community — simple and familiar',
      'A mobile app — fast, dedicated, and always on my phone',
      'A website — easy to open from any browser, no download needed',
      'Any of the above — I just want it to actually work',
    ],
  },
  {
    id: 'whatsapp_daily',
    type: 'single-choice',
    category: 'Platform Preference',
    question: 'How often do you use WhatsApp every day?',
    subtitle: 'This tells us how central WhatsApp already is to your daily life as a student.',
    options: [
      'All day — it never leaves my hand',
      'Several times a day — I check it constantly',
      'Once or twice a day — I use it but not obsessively',
      'Occasionally — I prefer calls or other apps',
    ],
  },
  {
    id: 'one_improvement',
    type: 'open-text',
    category: 'Your Vision',
    question: 'If you had the power to improve ONE thing about buying and selling in Enugu — what would it be?',
    subtitle: 'No wrong answers. Dream big. This shapes everything we build.',
    placeholder: 'e.g. I wish there was a trusted platform where students could buy and sell safely without being cheated...',
  },
];

export const TOTAL_QUESTIONS = QUESTIONS.length;
